/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    events: Event;
    media: Media;
    categories: Category;
    sponsors: Sponsor;
    volunteers: Volunteer;
    'contact-submissions': ContactSubmission;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'nyansa-futures': NyansaFuture;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'nyansa-futures': NyansaFuturesSelect<false> | NyansaFuturesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'featuredEvent' | 'pageHero';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    /**
     * Small label shown above the title (e.g. "Govern / Innovate / Transform" or "[Events]").
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Main heading. Line breaks are preserved.
     */
    heading?: string | null;
    /**
     * Optional final line of the heading rendered in the accent color.
     */
    headingAccent?: string | null;
    subtitle?: string | null;
    ctas?:
      | {
          label: string;
          /**
           * Internal path (e.g. /events) or external URL.
           */
          href?: string | null;
          variant?: ('primary' | 'outline') | null;
          /**
           * If enabled and an upcoming event is found, this button links to that event's Luma URL.
           */
          useEventLumaUrl?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Displays date, location and countdown for the next upcoming event.
     */
    bindNextEvent?: boolean | null;
    /**
     * Shown when no upcoming event exists or when binding is disabled.
     */
    fallbackImage?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | SplitContentBlock
    | StatementSectionBlock
    | ObjectivesGridBlock
    | ProgramsGridBlock
    | StatsRowBlock
    | TimelineStepsBlock
    | RolesListBlock
    | TestimonialListBlock
    | FAQBlockType
    | ContactInfoBlockType
    | UpcomingEventsBlockType
    | FeaturedEventBlockType
    | PastEventsBlockType
    | LatestArticlesBlockType
    | FeaturedSponsorsBlockType
    | NewsletterFormBlockType
    | ContactFormBlockType
    | VolunteerFormBlockType
    | SponsorInquiryFormBlockType
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  articleType?: ('commentary' | 'explainer' | 'event-summary' | 'research' | 'policy') | null;
  /**
   * Display this article prominently on the homepage
   */
  featured?: boolean | null;
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock".
 */
export interface SplitContentBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Optional. Shown on a second line after the heading in the primary-deep accent color (e.g. "Futures").
   */
  headingAccent?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  imagePosition?: ('left' | 'right') | null;
  background?: ('secondary' | 'white' | 'primary' | 'dark') | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementSectionBlock".
 */
export interface StatementSectionBlock {
  eyebrow?: string | null;
  /**
   * Primary heading. Line breaks in the text become <br/> in the output.
   */
  heading?: string | null;
  /**
   * Optional action button shown to the right of the heading at the top.
   */
  sideCta?: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
    };
  };
  /**
   * Small title above the body copy.
   */
  subheading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show the decorative chevron icon above the body.
   */
  showIcon?: boolean | null;
  image?: (number | null) | Media;
  background?: ('secondary' | 'white' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statementSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ObjectivesGridBlock".
 */
export interface ObjectivesGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        /**
         * e.g. "01", "02"
         */
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'objectivesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock".
 */
export interface ProgramsGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  background?: ('primary' | 'white' | 'secondary' | 'dark') | null;
  columns?: ('1' | '2' | '3' | '4') | null;
  items?:
    | {
        title: string;
        description: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'programsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock".
 */
export interface StatsRowBlock {
  heading?: string | null;
  items?:
    | {
        /**
         * e.g. "500+", "12"
         */
        number: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineStepsBlock".
 */
export interface TimelineStepsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timelineSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RolesListBlock".
 */
export interface RolesListBlock {
  eyebrow?: string | null;
  heading?: string | null;
  roles?:
    | {
        title: string;
        /**
         * e.g. "4-6 hrs / month"
         */
        commitment?: string | null;
        description: string;
        skills?:
          | {
              skill: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rolesList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialListBlock".
 */
export interface TestimonialListBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType".
 */
export interface FAQBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlockType".
 */
export interface ContactInfoBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  /**
   * Pulled from Site Settings > Contact Info.
   */
  showEmail?: boolean | null;
  showPhone?: boolean | null;
  showAddress?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingEventsBlockType".
 */
export interface UpcomingEventsBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  variant?: ('grid' | 'numberedList') | null;
  /**
   * When enabled, the first upcoming event is skipped (useful when a Featured Event block is rendering it above).
   */
  skipFirst?: boolean | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'upcomingEvents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedEventBlockType".
 */
export interface FeaturedEventBlockType {
  eyebrow?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredEvent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PastEventsBlockType".
 */
export interface PastEventsBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pastEvents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestArticlesBlockType".
 */
export interface LatestArticlesBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestArticles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedSponsorsBlockType".
 */
export interface FeaturedSponsorsBlockType {
  heading?: string | null;
  limit?: number | null;
  /**
   * Only show sponsors marked as "Show on Homepage".
   */
  featuredOnly?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredSponsors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterFormBlockType".
 */
export interface NewsletterFormBlockType {
  heading?: string | null;
  subheading?: string | null;
  variant?: ('full' | 'compact') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlockType".
 */
export interface ContactFormBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VolunteerFormBlockType".
 */
export interface VolunteerFormBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'volunteerForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorInquiryFormBlockType".
 */
export interface SponsorInquiryFormBlockType {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sponsorInquiryForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  eventType: 'ai-watch' | 'nyansa-futures' | 'beyond-the-algorithm' | 'other';
  date: string;
  endDate?: string | null;
  location?: string | null;
  isVirtual?: boolean | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  speakers?:
    | {
        name: string;
        title?: string | null;
        bio?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  agenda?:
    | {
        time: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to the Luma event page for registration
   */
  lumaEventUrl?: string | null;
  /**
   * Optional: Luma embed URL for inline registration widget
   */
  lumaEmbedUrl?: string | null;
  /**
   * Select sponsors/partners associated with this event
   */
  partnerLogos?: (number | Sponsor)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  eventStatus: 'upcoming' | 'past' | 'cancelled';
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * External website link for the sponsor/partner
   */
  url?: string | null;
  type: 'sponsor' | 'knowledge-partner' | 'community-partner';
  description?: string | null;
  /**
   * Display this sponsor on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  city?: string | null;
  country?: string | null;
  areasOfInterest?:
    | ('event-support' | 'research-writing' | 'media-communications' | 'community-outreach' | 'logistics')[]
    | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  source?: ('contact-form' | 'sponsor-inquiry') | null;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  organization?: string | null;
  jobTitle?: string | null;
  partnershipInterest?:
    | ('sponsorship' | 'knowledge-partnership' | 'community-partnership' | 'in-kind-support' | 'other')
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: number | Volunteer;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        eyebrow?: T;
        title?: T;
        heading?: T;
        headingAccent?: T;
        subtitle?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              useEventLumaUrl?: T;
              id?: T;
            };
        bindNextEvent?: T;
        fallbackImage?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        splitContent?: T | SplitContentBlockSelect<T>;
        statementSection?: T | StatementSectionBlockSelect<T>;
        objectivesGrid?: T | ObjectivesGridBlockSelect<T>;
        programsGrid?: T | ProgramsGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        timelineSteps?: T | TimelineStepsBlockSelect<T>;
        rolesList?: T | RolesListBlockSelect<T>;
        testimonialList?: T | TestimonialListBlockSelect<T>;
        faqBlock?: T | FAQBlockTypeSelect<T>;
        contactInfo?: T | ContactInfoBlockTypeSelect<T>;
        upcomingEvents?: T | UpcomingEventsBlockTypeSelect<T>;
        featuredEvent?: T | FeaturedEventBlockTypeSelect<T>;
        pastEvents?: T | PastEventsBlockTypeSelect<T>;
        latestArticles?: T | LatestArticlesBlockTypeSelect<T>;
        featuredSponsors?: T | FeaturedSponsorsBlockTypeSelect<T>;
        newsletterForm?: T | NewsletterFormBlockTypeSelect<T>;
        contactForm?: T | ContactFormBlockTypeSelect<T>;
        volunteerForm?: T | VolunteerFormBlockTypeSelect<T>;
        sponsorInquiryForm?: T | SponsorInquiryFormBlockTypeSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock_select".
 */
export interface SplitContentBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  image?: T;
  imagePosition?: T;
  background?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementSectionBlock_select".
 */
export interface StatementSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  sideCta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  subheading?: T;
  body?: T;
  showIcon?: T;
  image?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ObjectivesGridBlock_select".
 */
export interface ObjectivesGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock_select".
 */
export interface ProgramsGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  background?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock_select".
 */
export interface StatsRowBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineStepsBlock_select".
 */
export interface TimelineStepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RolesListBlock_select".
 */
export interface RolesListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  roles?:
    | T
    | {
        title?: T;
        commitment?: T;
        description?: T;
        skills?:
          | T
          | {
              skill?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialListBlock_select".
 */
export interface TestimonialListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType_select".
 */
export interface FAQBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlockType_select".
 */
export interface ContactInfoBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  showEmail?: T;
  showPhone?: T;
  showAddress?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingEventsBlockType_select".
 */
export interface UpcomingEventsBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  variant?: T;
  skipFirst?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedEventBlockType_select".
 */
export interface FeaturedEventBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PastEventsBlockType_select".
 */
export interface PastEventsBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestArticlesBlockType_select".
 */
export interface LatestArticlesBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedSponsorsBlockType_select".
 */
export interface FeaturedSponsorsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  featuredOnly?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterFormBlockType_select".
 */
export interface NewsletterFormBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlockType_select".
 */
export interface ContactFormBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VolunteerFormBlockType_select".
 */
export interface VolunteerFormBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorInquiryFormBlockType_select".
 */
export interface SponsorInquiryFormBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  articleType?: T;
  featured?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  eventType?: T;
  date?: T;
  endDate?: T;
  location?: T;
  isVirtual?: T;
  description?: T;
  heroImage?: T;
  speakers?:
    | T
    | {
        name?: T;
        title?: T;
        bio?: T;
        photo?: T;
        id?: T;
      };
  agenda?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  lumaEventUrl?: T;
  lumaEmbedUrl?: T;
  partnerLogos?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  eventStatus?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  type?: T;
  description?: T;
  featured?: T;
  sortOrder?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  country?: T;
  areasOfInterest?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  source?: T;
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  organization?: T;
  jobTitle?: T;
  partnershipInterest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Primary call-to-action button shown on the right side of the header.
   */
  ctaButton: {
    enabled?: boolean | null;
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Groups of links shown as columns in the footer.
   */
  linkColumns?:
    | {
        heading: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Newsletter block shown in the footer.
   */
  newsletter?: {
    heading?: string | null;
    subheading?: string | null;
  };
  /**
   * Use {year} as a placeholder for the current year.
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  branding?: {
    /**
     * Used in the header and footer. Uploaded file replaces /logo.png.
     */
    logo?: (number | null) | Media;
    /**
     * Optional. Used on dark sections (e.g. header with bg-dark). Falls back to primary logo if empty.
     */
    logoDark?: (number | null) | Media;
    /**
     * Desktop logo height in pixels (mobile auto-scales to ~70%).
     */
    logoHeight?: number | null;
    /**
     * Optional. Replaces the default favicon. Accepts .ico, .svg, or .png.
     */
    favicon?: (number | null) | Media;
  };
  theme?: {
    colors?: {
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      background?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      foreground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      dark?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      darkForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      card?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      cardForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      popover?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      popoverForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      primary?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      primaryForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      primaryDeep?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      secondary?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      secondaryForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      muted?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      mutedForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      accent?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      accentForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      destructive?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      destructiveForeground?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      border?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      input?: string | null;
      /**
       * OKLCH, HSL, RGB, or hex. Example: oklch(82% 0.17 85deg) or #ffcc00
       */
      ring?: string | null;
    };
    typography?: {
      fontSans?: ('sora' | 'inter' | 'manrope' | 'dm-sans' | 'space-grotesk' | 'ibm-plex-sans') | null;
      fontMono?: ('space-mono' | 'jetbrains-mono' | 'ibm-plex-mono') | null;
    };
    layout?: {
      /**
       * Border radius in pixels. 0 = sharp corners.
       */
      radius?: number | null;
      /**
       * Maximum container width in pixels at lg breakpoint and above.
       */
      containerMaxWidth?: number | null;
    };
  };
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    facebook?: string | null;
  };
  /**
   * Can also be set via MAILCHIMP_AUDIENCE_ID environment variable. This field overrides the env var.
   */
  mailchimpAudienceId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nyansa-futures".
 */
export interface NyansaFuture {
  id: number;
  headline?: string | null;
  subheadline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whyItMatters?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whoShouldAttend?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * e.g., Two-day hybrid conference
   */
  format?: string | null;
  keyThemes?:
    | {
        theme: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  expectedOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  attendUrl?: string | null;
  /**
   * Defaults to /become-a-sponsor if left empty
   */
  sponsorUrl?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        enabled?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  linkColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subheading?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  branding?:
    | T
    | {
        logo?: T;
        logoDark?: T;
        logoHeight?: T;
        favicon?: T;
      };
  theme?:
    | T
    | {
        colors?:
          | T
          | {
              background?: T;
              foreground?: T;
              dark?: T;
              darkForeground?: T;
              card?: T;
              cardForeground?: T;
              popover?: T;
              popoverForeground?: T;
              primary?: T;
              primaryForeground?: T;
              primaryDeep?: T;
              secondary?: T;
              secondaryForeground?: T;
              muted?: T;
              mutedForeground?: T;
              accent?: T;
              accentForeground?: T;
              destructive?: T;
              destructiveForeground?: T;
              border?: T;
              input?: T;
              ring?: T;
            };
        typography?:
          | T
          | {
              fontSans?: T;
              fontMono?: T;
            };
        layout?:
          | T
          | {
              radius?: T;
              containerMaxWidth?: T;
            };
      };
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        instagram?: T;
        youtube?: T;
        facebook?: T;
      };
  mailchimpAudienceId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nyansa-futures_select".
 */
export interface NyansaFuturesSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  description?: T;
  whyItMatters?: T;
  whoShouldAttend?: T;
  heroImage?: T;
  format?: T;
  keyThemes?:
    | T
    | {
        theme?: T;
        description?: T;
        id?: T;
      };
  expectedOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  attendUrl?: T;
  sponsorUrl?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}